# [namespace_registries]
# [package_registry_overrides]
# [registry]

# The default registry to use when none is specified. Generally this is wasi.dev, but can be set
# for cases when a company wants to use a private/internal registry.
default_registry = "omnia.host"

# namespace prefix mappings to registry (e.g. "wasi" part of "wasi:http")
[namespace_registries]
wasi = "wasi.dev"
# TODO: use well-known metadata file that can be used to determine the registry to use
omnia = { registry = "omnia.host", metadata = { preferredProtocol = "oci", "oci" = { registry = "ghcr.io", namespacePrefix = "augentic/" } } }

# This overrides the default registry for a specific package. This is useful for cases where a 
# package is published to multiple registries. 
[package_registry_overrides]
# "wasi:blobstore" = { registry = "omnia", metadata = { preferredProtocol = "oci", "oci" = { registry = "ghcr.io", namespacePrefix = "augentic/" } } }
# "wasi:keyvalue" = { registry = "omnia", metadata = { preferredProtocol = "oci", "oci" = { registry = "ghcr.io", namespacePrefix = "augentic/" } } }
# "wasi:messaging" = { registry = "omnia", metadata = { preferredProtocol = "oci", "oci" = { registry = "ghcr.io", namespacePrefix = "augentic/" } } }
# "wasi:sql" = { registry = "omnia", metadata = { preferredProtocol = "oci", "oci" = { registry = "ghcr.io", namespacePrefix = "augentic/" } } }

# "wasi:blobstore" = "omnia.host"

[registry."omnia.host"]

[registry."omnia.host".oci]
config_file = "config.toml"
